apiVersion: v1
kind: Service
metadata:
  name: leaderboard
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80 # Ensure the container's internal port is 80 for leaderboard service
  selector:
    app: leaderboard
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000 # Update this to match the port your app is actually listening on inside the pod
  selector:
    app: web
